# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_principal(object):
    def setupUi(self, ventana_principal):
        ventana_principal.setObjectName("ventana_principal")
        ventana_principal.resize(600, 400)
        ventana_principal.setMinimumSize(QtCore.QSize(600, 400))
        ventana_principal.setMaximumSize(QtCore.QSize(600, 400))
        ventana_principal.setStyleSheet("#panel_derecha{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#frame{\n"
"    background-color: transparent;\n"
"}\n"
"[objectName ^=\"lbl\"]{\n"
"    color: rgb(0, 0, 0);\n"
"    font-family : Arial;\n"
"    font-size:16px;\n"
"}\n"
"[objectName ^=\"txt\"] {\n"
"    color: rgb(255, 255, 255);\n"
"    font-family : Arial;\n"
"    font-size:14px;\n"
"    border:0px;\n"
"    background-color: rgb(184, 184, 184);\n"
"}\n"
"#panel_principal{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"#panel_izquierda{\n"
"    background-color: rgb(180, 191, 204);\n"
"}\n"
"#btn_ingresar{\n"
"    border-radius: 5px;\n"
"    background-color: rgb(0, 102, 140);\n"
"    min-height: 30px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 14px;\n"
"    font-family: Arial;\n"
"    font-weight: bold;\n"
"}\n"
"#btn_ingresar::hover{\n"
"    background-color: rgb(82, 116, 250);\n"
"}\n"
"#lbr_recuperar_credenciales{\n"
"    font-size: 12px;\n"
"    color: rgb(0, 0, 0);\n"
"    font-family : Arial;\n"
"    text-decoration:underline;\n"
"}\n"
"#btn_cerrar{\n"
"    background-color:  transparent;\n"
"    border:None;\n"
"}")
        self.panel_principal = QtWidgets.QWidget(ventana_principal)
        self.panel_principal.setObjectName("panel_principal")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.panel_principal)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel_secundario = QtWidgets.QWidget(self.panel_principal)
        self.panel_secundario.setObjectName("panel_secundario")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.panel_secundario)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.panel_izquierda = QtWidgets.QWidget(self.panel_secundario)
        self.panel_izquierda.setMinimumSize(QtCore.QSize(300, 0))
        self.panel_izquierda.setMaximumSize(QtCore.QSize(300, 16777215))
        self.panel_izquierda.setStyleSheet("")
        self.panel_izquierda.setObjectName("panel_izquierda")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.panel_izquierda)
        self.verticalLayout_2.setContentsMargins(25, 25, 25, 25)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.img_fondo = QtWidgets.QLabel(self.panel_izquierda)
        self.img_fondo.setStyleSheet("")
        self.img_fondo.setText("")
        self.img_fondo.setTextFormat(QtCore.Qt.PlainText)
        self.img_fondo.setPixmap(QtGui.QPixmap("../Source/Dev_Rous_SF.png"))
        self.img_fondo.setScaledContents(True)
        self.img_fondo.setWordWrap(False)
        self.img_fondo.setObjectName("img_fondo")
        self.verticalLayout_2.addWidget(self.img_fondo)
        self.horizontalLayout.addWidget(self.panel_izquierda)
        self.panel_derecha = QtWidgets.QWidget(self.panel_secundario)
        self.panel_derecha.setMinimumSize(QtCore.QSize(300, 0))
        self.panel_derecha.setMaximumSize(QtCore.QSize(300, 16777215))
        self.panel_derecha.setObjectName("panel_derecha")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.panel_derecha)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.panel_derecha)
        self.widget.setMinimumSize(QtCore.QSize(0, 35))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 35))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 5, 5, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setMinimumSize(QtCore.QSize(25, 25))
        self.widget_5.setMaximumSize(QtCore.QSize(25, 25))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_cerrar = QtWidgets.QPushButton(self.widget_5)
        self.btn_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cerrar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Downloads/cclose_img.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon)
        self.btn_cerrar.setIconSize(QtCore.QSize(20, 20))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.gridLayout_2.addWidget(self.btn_cerrar, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.verticalLayout_3.addWidget(self.widget)
        self.frame = QtWidgets.QFrame(self.panel_derecha)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(80, -1, 80, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.img_login = QtWidgets.QLabel(self.frame)
        self.img_login.setText("")
        self.img_login.setPixmap(QtGui.QPixmap("../../../PruebasCodigo-master/icons/user-shield.svg"))
        self.img_login.setScaledContents(True)
        self.img_login.setAlignment(QtCore.Qt.AlignCenter)
        self.img_login.setObjectName("img_login")
        self.gridLayout.addWidget(self.img_login, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.widget_2 = QtWidgets.QWidget(self.panel_derecha)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(30, 0, 30, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_usuario = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_usuario.setFont(font)
        self.lbl_usuario.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbl_usuario.setObjectName("lbl_usuario")
        self.verticalLayout_4.addWidget(self.lbl_usuario)
        self.txt_usuario = QtWidgets.QLineEdit(self.widget_2)
        self.txt_usuario.setMinimumSize(QtCore.QSize(0, 25))
        self.txt_usuario.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.txt_usuario.setFont(font)
        self.txt_usuario.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txt_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_usuario.setObjectName("txt_usuario")
        self.verticalLayout_4.addWidget(self.txt_usuario)
        self.lbl_contrasena = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_contrasena.setFont(font)
        self.lbl_contrasena.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbl_contrasena.setObjectName("lbl_contrasena")
        self.verticalLayout_4.addWidget(self.lbl_contrasena)
        self.txt_contrasena = QtWidgets.QLineEdit(self.widget_2)
        self.txt_contrasena.setMinimumSize(QtCore.QSize(0, 25))
        self.txt_contrasena.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        self.txt_contrasena.setFont(font)
        self.txt_contrasena.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txt_contrasena.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_contrasena.setObjectName("txt_contrasena")
        self.verticalLayout_4.addWidget(self.txt_contrasena)
        self.lbl_datos_incorrectos = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setItalic(True)
        self.lbl_datos_incorrectos.setFont(font)
        self.lbl_datos_incorrectos.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbl_datos_incorrectos.setText("")
        self.lbl_datos_incorrectos.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_datos_incorrectos.setObjectName("lbl_datos_incorrectos")
        self.verticalLayout_4.addWidget(self.lbl_datos_incorrectos)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_ingresar = QtWidgets.QPushButton(self.widget_4)
        self.btn_ingresar.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_ingresar.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ingresar.setFont(font)
        self.btn_ingresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ingresar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btn_ingresar.setObjectName("btn_ingresar")
        self.horizontalLayout_2.addWidget(self.btn_ingresar)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.lbr_recuperar_credenciales = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setItalic(True)
        font.setUnderline(True)
        self.lbr_recuperar_credenciales.setFont(font)
        self.lbr_recuperar_credenciales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbr_recuperar_credenciales.setMouseTracking(True)
        self.lbr_recuperar_credenciales.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbr_recuperar_credenciales.setAlignment(QtCore.Qt.AlignCenter)
        self.lbr_recuperar_credenciales.setObjectName("lbr_recuperar_credenciales")
        self.verticalLayout_4.addWidget(self.lbr_recuperar_credenciales)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.panel_derecha)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 15))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 15))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.panel_derecha)
        self.verticalLayout.addWidget(self.panel_secundario)
        ventana_principal.setCentralWidget(self.panel_principal)

        self.retranslateUi(ventana_principal)
        QtCore.QMetaObject.connectSlotsByName(ventana_principal)

    def retranslateUi(self, ventana_principal):
        _translate = QtCore.QCoreApplication.translate
        ventana_principal.setWindowTitle(_translate("ventana_principal", "MainWindow"))
        self.lbl_usuario.setText(_translate("ventana_principal", "Usuario"))
        self.txt_usuario.setPlaceholderText(_translate("ventana_principal", "Ingresar Usuario"))
        self.lbl_contrasena.setText(_translate("ventana_principal", "Contraseña"))
        self.txt_contrasena.setPlaceholderText(_translate("ventana_principal", "Ingresar Contraseña"))
        self.btn_ingresar.setText(_translate("ventana_principal", "Ingresar"))
        self.lbr_recuperar_credenciales.setText(_translate("ventana_principal", "Recuperar credenciales"))
