# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal_trabajo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_de_trabajo(object):
    def setupUi(self, ventana_de_trabajo):
        ventana_de_trabajo.setObjectName("ventana_de_trabajo")
        ventana_de_trabajo.resize(1064, 600)
        ventana_de_trabajo.setStyleSheet("#logo{\n"
"    max-width:90px;\n"
"    max-height: 20px;\n"
"    margin-left: 10px;\n"
"}\n"
"#img_logo{\n"
"    /*padding-top:100px;\n"
"    padding-bottom:100px;\n"
"    padding-left:150px;\n"
"    padding-right:150px;*/\n"
"    min_width:450px;\n"
"    max-width:700px;\n"
"    \n"
"}\n"
"[objectName^=\"panel\"] {\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"[objectName^=\"txt\"] {\n"
"    background-color: rgb(245, 245, 245);\n"
"    border-bottom: 1px solid rgb(183, 183, 183);\n"
"    border-top: 0px;\n"
"    font-size: 14px;\n"
"    font-family: Arial, sans-serif;\n"
"}\n"
"[objectName^=\"btn_btn\"] {\n"
"background-color: rgb(204, 204, 204);\n"
"    border-radius: 4px;\n"
"    min-height: 25px;\n"
"    max-height: 35px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    font-size:14px;\n"
"    font-family: Arial;\n"
"}\n"
"[objectName^=\"lbt\"] {\n"
"    font-size:16px;\n"
"    font-family: Arial, sans-serif;\n"
"    font-weight: bold;\n"
"}\n"
"[objectName^=\"lbl\"] {\n"
"    font-size:14px;\n"
"    font-family: Arial, sans-serif;\n"
"}\n"
"[objectName^=\"btn_btn\"]:hover {\n"
"background-color: rgb(191, 191, 191);\n"
"}\n"
"[objectName^=\"bts_bts\"] {\n"
"background-color: rgb(230, 230, 230);\n"
"border-radius:5px;\n"
"min-width:70px;\n"
"font-size:12px;\n"
"    font-family: Arial;\n"
"}\n"
"[objectName^=\"bts_bts\"]:hover {\n"
"background-color: rgb(212, 234, 247);\n"
"}\n"
"[objectName^=\"btn_btn_ingresa\"] {\n"
"background-color: rgb(33, 195, 47);\n"
"}\n"
"[objectName^=\"btn_btn_ingresa\"]:hover {\n"
"background-color: rgb(36, 213, 50);\n"
"}\n"
"[objectName^=\"btn_btn_editar\"] {\n"
"background-color: rgb(72, 95, 199);\n"
"}\n"
"[objectName^=\"btn_btn_editar\"]:hover {\n"
"background-color: rgb(81, 108, 226);\n"
"}\n"
"[objectName^=\"btn_btn_eliminar\"] {\n"
"background-color: rgb(229, 46, 46);\n"
"}\n"
"[objectName^=\"btn_btn_eliminar\"]:hover {\n"
"background-color: rgb(248, 49, 49);\n"
"}\n"
"#panel_cabecera{\n"
"background-color: rgb(204, 203, 200);\n"
"max-height: 35px;\n"
"}\n"
"#btn_minimizar{\n"
"    background-color:transparent;\n"
"}\n"
"#btn_maximizar{\n"
"    background-color:transparent;\n"
"}\n"
"#btn_cerrar{\n"
"    background-color:transparent;\n"
"}\n"
"#btn_btn_menu{\n"
"    margin-left:5px;\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"}\n"
"#btn_btn_menu:hover {\n"
"background-color: rgb(212, 234, 247);\n"
"}\n"
"#btn_btn_cuenta{\n"
"    background-color:Transparent;\n"
"}\n"
"#panel_opciones_desplegable{\n"
"background-color: rgb(245, 244, 241);\n"
"border-right: 1px solid  rgb(204, 203, 200);\n"
"max-width:0px;\n"
"}\n"
"#panel_opciones_superior{\n"
"    max-height:40px;\n"
"    padding-bottom: 0px;\n"
"    padding-top: 0px;\n"
"}\n"
"#panel_contenido_opciones_superior{\n"
"max-height: 40px;\n"
"}\n"
"\n"
"#panel_paginas{\n"
"padding:15px;\n"
"}")
        self.panel_centralwidget = QtWidgets.QWidget(ventana_de_trabajo)
        self.panel_centralwidget.setObjectName("panel_centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.panel_centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.panel_cabecera = QtWidgets.QWidget(self.panel_centralwidget)
        self.panel_cabecera.setObjectName("panel_cabecera")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.panel_cabecera)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QLabel(self.panel_cabecera)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../../../../../Downloads/logo_sinfondo_vector.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        spacerItem = QtWidgets.QSpacerItem(869, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_minimizar = QtWidgets.QPushButton(self.panel_cabecera)
        self.btn_minimizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Downloads/minimizar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimizar.setIcon(icon)
        self.btn_minimizar.setIconSize(QtCore.QSize(20, 20))
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.horizontalLayout.addWidget(self.btn_minimizar)
        self.btn_maximizar = QtWidgets.QPushButton(self.panel_cabecera)
        self.btn_maximizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_maximizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../Downloads/maximizar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximizar.setIcon(icon1)
        self.btn_maximizar.setIconSize(QtCore.QSize(20, 20))
        self.btn_maximizar.setObjectName("btn_maximizar")
        self.horizontalLayout.addWidget(self.btn_maximizar)
        self.btn_cerrar = QtWidgets.QPushButton(self.panel_cabecera)
        self.btn_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cerrar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../Downloads/img_cerrar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon2)
        self.btn_cerrar.setIconSize(QtCore.QSize(20, 20))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout.addWidget(self.btn_cerrar)
        self.gridLayout.addWidget(self.panel_cabecera, 0, 0, 1, 1)
        self.panel_ventana = QtWidgets.QWidget(self.panel_centralwidget)
        self.panel_ventana.setStyleSheet("")
        self.panel_ventana.setObjectName("panel_ventana")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.panel_ventana)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.panel_opciones_desplegable = QtWidgets.QWidget(self.panel_ventana)
        self.panel_opciones_desplegable.setMinimumSize(QtCore.QSize(0, 0))
        self.panel_opciones_desplegable.setMaximumSize(QtCore.QSize(1, 16777215))
        self.panel_opciones_desplegable.setStyleSheet("")
        self.panel_opciones_desplegable.setObjectName("panel_opciones_desplegable")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.panel_opciones_desplegable)
        self.verticalLayout_16.setContentsMargins(2, 2, 2, 0)
        self.verticalLayout_16.setSpacing(2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.panel_sub_opciones_desplegable = QtWidgets.QWidget(self.panel_opciones_desplegable)
        self.panel_sub_opciones_desplegable.setObjectName("panel_sub_opciones_desplegable")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.panel_sub_opciones_desplegable)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.btn_btn_cuenta = QtWidgets.QPushButton(self.panel_sub_opciones_desplegable)
        self.btn_btn_cuenta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_cuenta.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../Downloads/cuenta.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_cuenta.setIcon(icon3)
        self.btn_btn_cuenta.setIconSize(QtCore.QSize(40, 40))
        self.btn_btn_cuenta.setFlat(False)
        self.btn_btn_cuenta.setObjectName("btn_btn_cuenta")
        self.verticalLayout_17.addWidget(self.btn_btn_cuenta)
        self.bts_bts_venta = QtWidgets.QToolButton(self.panel_sub_opciones_desplegable)
        self.bts_bts_venta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../Downloads/venta.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bts_bts_venta.setIcon(icon4)
        self.bts_bts_venta.setIconSize(QtCore.QSize(25, 25))
        self.bts_bts_venta.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.bts_bts_venta.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bts_bts_venta.setAutoRaise(False)
        self.bts_bts_venta.setObjectName("bts_bts_venta")
        self.verticalLayout_17.addWidget(self.bts_bts_venta)
        self.bts_bts_inventario = QtWidgets.QToolButton(self.panel_sub_opciones_desplegable)
        self.bts_bts_inventario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../Downloads/inventory_black_24dp.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bts_bts_inventario.setIcon(icon5)
        self.bts_bts_inventario.setIconSize(QtCore.QSize(25, 25))
        self.bts_bts_inventario.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bts_bts_inventario.setObjectName("bts_bts_inventario")
        self.verticalLayout_17.addWidget(self.bts_bts_inventario)
        self.bts_bts_clientes = QtWidgets.QToolButton(self.panel_sub_opciones_desplegable)
        self.bts_bts_clientes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../Downloads/clientes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bts_bts_clientes.setIcon(icon6)
        self.bts_bts_clientes.setIconSize(QtCore.QSize(25, 25))
        self.bts_bts_clientes.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bts_bts_clientes.setObjectName("bts_bts_clientes")
        self.verticalLayout_17.addWidget(self.bts_bts_clientes)
        self.bts_bts_proveedor = QtWidgets.QToolButton(self.panel_sub_opciones_desplegable)
        self.bts_bts_proveedor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../../Downloads/proveedor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bts_bts_proveedor.setIcon(icon7)
        self.bts_bts_proveedor.setIconSize(QtCore.QSize(25, 25))
        self.bts_bts_proveedor.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bts_bts_proveedor.setObjectName("bts_bts_proveedor")
        self.verticalLayout_17.addWidget(self.bts_bts_proveedor)
        self.bts_bts_compras = QtWidgets.QToolButton(self.panel_sub_opciones_desplegable)
        self.bts_bts_compras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../../../../Downloads/compras.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bts_bts_compras.setIcon(icon8)
        self.bts_bts_compras.setIconSize(QtCore.QSize(25, 25))
        self.bts_bts_compras.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bts_bts_compras.setObjectName("bts_bts_compras")
        self.verticalLayout_17.addWidget(self.bts_bts_compras)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem1)
        self.verticalLayout_16.addWidget(self.panel_sub_opciones_desplegable)
        self.horizontalLayout_2.addWidget(self.panel_opciones_desplegable)
        self.panel_principal_cuerpo = QtWidgets.QWidget(self.panel_ventana)
        self.panel_principal_cuerpo.setObjectName("panel_principal_cuerpo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.panel_principal_cuerpo)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel_opciones_superior = QtWidgets.QWidget(self.panel_principal_cuerpo)
        self.panel_opciones_superior.setMinimumSize(QtCore.QSize(0, 0))
        self.panel_opciones_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.panel_opciones_superior.setStyleSheet("")
        self.panel_opciones_superior.setObjectName("panel_opciones_superior")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.panel_opciones_superior)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.panel_contenido_opciones_superior = QtWidgets.QWidget(self.panel_opciones_superior)
        self.panel_contenido_opciones_superior.setMinimumSize(QtCore.QSize(0, 0))
        self.panel_contenido_opciones_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.panel_contenido_opciones_superior.setObjectName("panel_contenido_opciones_superior")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.panel_contenido_opciones_superior)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.panel_btn_menu = QtWidgets.QWidget(self.panel_contenido_opciones_superior)
        self.panel_btn_menu.setMinimumSize(QtCore.QSize(40, 40))
        self.panel_btn_menu.setMaximumSize(QtCore.QSize(40, 40))
        self.panel_btn_menu.setObjectName("panel_btn_menu")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.panel_btn_menu)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_btn_menu = QtWidgets.QPushButton(self.panel_btn_menu)
        self.btn_btn_menu.setMinimumSize(QtCore.QSize(40, 25))
        self.btn_btn_menu.setMaximumSize(QtCore.QSize(40, 35))
        self.btn_btn_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_menu.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../../../Downloads/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_menu.setIcon(icon9)
        self.btn_btn_menu.setIconSize(QtCore.QSize(30, 30))
        self.btn_btn_menu.setObjectName("btn_btn_menu")
        self.horizontalLayout_4.addWidget(self.btn_btn_menu)
        self.horizontalLayout_8.addWidget(self.panel_btn_menu)
        spacerItem2 = QtWidgets.QSpacerItem(385, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.panel_contenido_opciones_superior)
        self.verticalLayout.addWidget(self.panel_opciones_superior)
        self.panel_cuerpo = QtWidgets.QWidget(self.panel_principal_cuerpo)
        self.panel_cuerpo.setObjectName("panel_cuerpo")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.panel_cuerpo)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.panel_paginas = QtWidgets.QStackedWidget(self.panel_cuerpo)
        self.panel_paginas.setObjectName("panel_paginas")
        self.panel_pagina_cuenta = QtWidgets.QWidget()
        self.panel_pagina_cuenta.setObjectName("panel_pagina_cuenta")
        self.label_3 = QtWidgets.QLabel(self.panel_pagina_cuenta)
        self.label_3.setGeometry(QtCore.QRect(60, 30, 47, 13))
        self.label_3.setObjectName("label_3")
        self.panel_paginas.addWidget(self.panel_pagina_cuenta)
        self.panel_logo = QtWidgets.QWidget()
        self.panel_logo.setObjectName("panel_logo")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.panel_logo)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.img_logo = QtWidgets.QLabel(self.panel_logo)
        self.img_logo.setText("")
        self.img_logo.setPixmap(QtGui.QPixmap("../../../../../Downloads/logo.png"))
        self.img_logo.setScaledContents(True)
        self.img_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.img_logo.setObjectName("img_logo")
        self.horizontalLayout_9.addWidget(self.img_logo)
        self.panel_paginas.addWidget(self.panel_logo)
        self.panel_pagina_compras = QtWidgets.QWidget()
        self.panel_pagina_compras.setObjectName("panel_pagina_compras")
        self.label = QtWidgets.QLabel(self.panel_pagina_compras)
        self.label.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.panel_pagina_compras)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.panel_paginas.addWidget(self.panel_pagina_compras)
        self.panel_pagina_clientes = QtWidgets.QWidget()
        self.panel_pagina_clientes.setObjectName("panel_pagina_clientes")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.panel_pagina_clientes)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lbt_clientes = QtWidgets.QLabel(self.panel_pagina_clientes)
        self.lbt_clientes.setObjectName("lbt_clientes")
        self.verticalLayout_13.addWidget(self.lbt_clientes)
        self.panel_datos_superiores = QtWidgets.QWidget(self.panel_pagina_clientes)
        self.panel_datos_superiores.setObjectName("panel_datos_superiores")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.panel_datos_superiores)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_idclientes = QtWidgets.QLabel(self.panel_datos_superiores)
        self.lbl_idclientes.setObjectName("lbl_idclientes")
        self.gridLayout_4.addWidget(self.lbl_idclientes, 0, 0, 1, 1)
        self.txt_id_cliente = QtWidgets.QLineEdit(self.panel_datos_superiores)
        self.txt_id_cliente.setObjectName("txt_id_cliente")
        self.gridLayout_4.addWidget(self.txt_id_cliente, 0, 1, 1, 1)
        self.lbl_nombreclientes = QtWidgets.QLabel(self.panel_datos_superiores)
        self.lbl_nombreclientes.setObjectName("lbl_nombreclientes")
        self.gridLayout_4.addWidget(self.lbl_nombreclientes, 1, 0, 1, 1)
        self.txt_nombre_cliente = QtWidgets.QLineEdit(self.panel_datos_superiores)
        self.txt_nombre_cliente.setObjectName("txt_nombre_cliente")
        self.gridLayout_4.addWidget(self.txt_nombre_cliente, 1, 1, 1, 4)
        self.btn_btn_buscar = QtWidgets.QPushButton(self.panel_datos_superiores)
        self.btn_btn_buscar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_buscar.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../../../Downloads/buscar_persona.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_buscar.setIcon(icon10)
        self.btn_btn_buscar.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_buscar.setObjectName("btn_btn_buscar")
        self.gridLayout_4.addWidget(self.btn_btn_buscar, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 4, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_4)
        self.panel_botones = QtWidgets.QWidget(self.panel_datos_superiores)
        self.panel_botones.setStyleSheet("")
        self.panel_botones.setObjectName("panel_botones")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.panel_botones)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_btn_ingresar = QtWidgets.QPushButton(self.panel_botones)
        self.btn_btn_ingresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../../../../Downloads/agregar_circulo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_ingresar.setIcon(icon11)
        self.btn_btn_ingresar.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_ingresar.setObjectName("btn_btn_ingresar")
        self.horizontalLayout_3.addWidget(self.btn_btn_ingresar)
        self.btn_btn_editar = QtWidgets.QPushButton(self.panel_botones)
        self.btn_btn_editar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../../../../Downloads/editar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_editar.setIcon(icon12)
        self.btn_btn_editar.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_editar.setObjectName("btn_btn_editar")
        self.horizontalLayout_3.addWidget(self.btn_btn_editar)
        self.btn_btn_eliminar = QtWidgets.QPushButton(self.panel_botones)
        self.btn_btn_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../../../../Downloads/eliminar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_eliminar.setIcon(icon13)
        self.btn_btn_eliminar.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_eliminar.setObjectName("btn_btn_eliminar")
        self.horizontalLayout_3.addWidget(self.btn_btn_eliminar)
        self.horizontalLayout_7.addWidget(self.panel_botones)
        self.verticalLayout_13.addWidget(self.panel_datos_superiores)
        self.panel_detalles = QtWidgets.QWidget(self.panel_pagina_clientes)
        self.panel_detalles.setObjectName("panel_detalles")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.panel_detalles)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(737, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.btn_btn_info = QtWidgets.QPushButton(self.panel_detalles)
        self.btn_btn_info.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../../../../Downloads/informacion.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_btn_info.setIcon(icon14)
        self.btn_btn_info.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_info.setObjectName("btn_btn_info")
        self.horizontalLayout_6.addWidget(self.btn_btn_info)
        self.verticalLayout_13.addWidget(self.panel_detalles)
        self.panel_tabla = QtWidgets.QWidget(self.panel_pagina_clientes)
        self.panel_tabla.setObjectName("panel_tabla")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.panel_tabla)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabla = QtWidgets.QTableWidget(self.panel_tabla)
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(0)
        self.tabla.setRowCount(0)
        self.horizontalLayout_5.addWidget(self.tabla)
        self.verticalLayout_13.addWidget(self.panel_tabla)
        self.panel_paginas.addWidget(self.panel_pagina_clientes)
        self.panel_pagina_venta = QtWidgets.QWidget()
        self.panel_pagina_venta.setObjectName("panel_pagina_venta")
        self.label_5 = QtWidgets.QLabel(self.panel_pagina_venta)
        self.label_5.setGeometry(QtCore.QRect(50, 40, 47, 13))
        self.label_5.setObjectName("label_5")
        self.panel_paginas.addWidget(self.panel_pagina_venta)
        self.panel_pagina_proveedores = QtWidgets.QWidget()
        self.panel_pagina_proveedores.setObjectName("panel_pagina_proveedores")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.panel_pagina_proveedores)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lbt_proveedores = QtWidgets.QLabel(self.panel_pagina_proveedores)
        self.lbt_proveedores.setObjectName("lbt_proveedores")
        self.verticalLayout_15.addWidget(self.lbt_proveedores)
        self.panel_datos_superiores_prove = QtWidgets.QWidget(self.panel_pagina_proveedores)
        self.panel_datos_superiores_prove.setObjectName("panel_datos_superiores_prove")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.panel_datos_superiores_prove)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.panel_datos_prove = QtWidgets.QGridLayout()
        self.panel_datos_prove.setObjectName("panel_datos_prove")
        self.lbl_idproveedores = QtWidgets.QLabel(self.panel_datos_superiores_prove)
        self.lbl_idproveedores.setObjectName("lbl_idproveedores")
        self.panel_datos_prove.addWidget(self.lbl_idproveedores, 0, 0, 1, 1)
        self.txt_id_prove = QtWidgets.QLineEdit(self.panel_datos_superiores_prove)
        self.txt_id_prove.setObjectName("txt_id_prove")
        self.panel_datos_prove.addWidget(self.txt_id_prove, 0, 1, 1, 1)
        self.lbl_nombreproveedores = QtWidgets.QLabel(self.panel_datos_superiores_prove)
        self.lbl_nombreproveedores.setObjectName("lbl_nombreproveedores")
        self.panel_datos_prove.addWidget(self.lbl_nombreproveedores, 1, 0, 1, 1)
        self.txt_nombre_prove = QtWidgets.QLineEdit(self.panel_datos_superiores_prove)
        self.txt_nombre_prove.setObjectName("txt_nombre_prove")
        self.panel_datos_prove.addWidget(self.txt_nombre_prove, 1, 1, 1, 4)
        self.btn_btn_buscar_proveedor = QtWidgets.QPushButton(self.panel_datos_superiores_prove)
        self.btn_btn_buscar_proveedor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_buscar_proveedor.setText("")
        self.btn_btn_buscar_proveedor.setIcon(icon10)
        self.btn_btn_buscar_proveedor.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_buscar_proveedor.setObjectName("btn_btn_buscar_proveedor")
        self.panel_datos_prove.addWidget(self.btn_btn_buscar_proveedor, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.panel_datos_prove.addItem(spacerItem5, 0, 4, 1, 1)
        self.horizontalLayout_13.addLayout(self.panel_datos_prove)
        self.panel_botones_prove = QtWidgets.QWidget(self.panel_datos_superiores_prove)
        self.panel_botones_prove.setStyleSheet("")
        self.panel_botones_prove.setObjectName("panel_botones_prove")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.panel_botones_prove)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btn_btn_ingresar_prove = QtWidgets.QPushButton(self.panel_botones_prove)
        self.btn_btn_ingresar_prove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_ingresar_prove.setIcon(icon11)
        self.btn_btn_ingresar_prove.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_ingresar_prove.setObjectName("btn_btn_ingresar_prove")
        self.horizontalLayout_14.addWidget(self.btn_btn_ingresar_prove)
        self.btn_btn_editar_prove = QtWidgets.QPushButton(self.panel_botones_prove)
        self.btn_btn_editar_prove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_editar_prove.setIcon(icon12)
        self.btn_btn_editar_prove.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_editar_prove.setObjectName("btn_btn_editar_prove")
        self.horizontalLayout_14.addWidget(self.btn_btn_editar_prove)
        self.btn_btn_eliminar_prove = QtWidgets.QPushButton(self.panel_botones_prove)
        self.btn_btn_eliminar_prove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_eliminar_prove.setIcon(icon13)
        self.btn_btn_eliminar_prove.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_eliminar_prove.setObjectName("btn_btn_eliminar_prove")
        self.horizontalLayout_14.addWidget(self.btn_btn_eliminar_prove)
        self.horizontalLayout_13.addWidget(self.panel_botones_prove)
        self.verticalLayout_15.addWidget(self.panel_datos_superiores_prove)
        self.panel_detalles_prove = QtWidgets.QWidget(self.panel_pagina_proveedores)
        self.panel_detalles_prove.setObjectName("panel_detalles_prove")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.panel_detalles_prove)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem6 = QtWidgets.QSpacerItem(737, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.btn_btn_info_3 = QtWidgets.QPushButton(self.panel_detalles_prove)
        self.btn_btn_info_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_btn_info_3.setIcon(icon14)
        self.btn_btn_info_3.setIconSize(QtCore.QSize(25, 25))
        self.btn_btn_info_3.setObjectName("btn_btn_info_3")
        self.horizontalLayout_15.addWidget(self.btn_btn_info_3)
        self.verticalLayout_15.addWidget(self.panel_detalles_prove)
        self.panel_tabla_prove = QtWidgets.QWidget(self.panel_pagina_proveedores)
        self.panel_tabla_prove.setObjectName("panel_tabla_prove")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.panel_tabla_prove)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.tabla_prove = QtWidgets.QTableWidget(self.panel_tabla_prove)
        self.tabla_prove.setObjectName("tabla_prove")
        self.tabla_prove.setColumnCount(0)
        self.tabla_prove.setRowCount(0)
        self.horizontalLayout_12.addWidget(self.tabla_prove)
        self.verticalLayout_15.addWidget(self.panel_tabla_prove)
        self.panel_paginas.addWidget(self.panel_pagina_proveedores)
        self.panel_pagina_inventario = QtWidgets.QWidget()
        self.panel_pagina_inventario.setObjectName("panel_pagina_inventario")
        self.label_4 = QtWidgets.QLabel(self.panel_pagina_inventario)
        self.label_4.setGeometry(QtCore.QRect(80, 20, 81, 16))
        self.label_4.setObjectName("label_4")
        self.panel_paginas.addWidget(self.panel_pagina_inventario)
        self.verticalLayout_14.addWidget(self.panel_paginas)
        self.verticalLayout.addWidget(self.panel_cuerpo)
        self.horizontalLayout_2.addWidget(self.panel_principal_cuerpo)
        self.gridLayout.addWidget(self.panel_ventana, 1, 0, 1, 1)
        ventana_de_trabajo.setCentralWidget(self.panel_centralwidget)

        self.retranslateUi(ventana_de_trabajo)
        self.panel_paginas.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(ventana_de_trabajo)

    def retranslateUi(self, ventana_de_trabajo):
        _translate = QtCore.QCoreApplication.translate
        ventana_de_trabajo.setWindowTitle(_translate("ventana_de_trabajo", "MainWindow"))
        self.bts_bts_venta.setText(_translate("ventana_de_trabajo", "Venta"))
        self.bts_bts_inventario.setText(_translate("ventana_de_trabajo", "Inventario"))
        self.bts_bts_clientes.setText(_translate("ventana_de_trabajo", "Clientes"))
        self.bts_bts_proveedor.setText(_translate("ventana_de_trabajo", "Provedores"))
        self.bts_bts_compras.setText(_translate("ventana_de_trabajo", "Compras"))
        self.label_3.setText(_translate("ventana_de_trabajo", "cuenta"))
        self.label.setText(_translate("ventana_de_trabajo", "Compras"))
        self.label_2.setText(_translate("ventana_de_trabajo", "TextLabel"))
        self.lbt_clientes.setText(_translate("ventana_de_trabajo", "Clientes"))
        self.lbl_idclientes.setText(_translate("ventana_de_trabajo", "Id. Cliente"))
        self.lbl_nombreclientes.setText(_translate("ventana_de_trabajo", "Nombre"))
        self.btn_btn_ingresar.setText(_translate("ventana_de_trabajo", "Agregar"))
        self.btn_btn_editar.setText(_translate("ventana_de_trabajo", "Modificar"))
        self.btn_btn_eliminar.setText(_translate("ventana_de_trabajo", "Eliminar"))
        self.btn_btn_info.setText(_translate("ventana_de_trabajo", "Detalles"))
        self.label_5.setText(_translate("ventana_de_trabajo", "venta"))
        self.lbt_proveedores.setText(_translate("ventana_de_trabajo", "Proveedores"))
        self.lbl_idproveedores.setText(_translate("ventana_de_trabajo", "Id. Cliente"))
        self.lbl_nombreproveedores.setText(_translate("ventana_de_trabajo", "Nombre"))
        self.btn_btn_ingresar_prove.setText(_translate("ventana_de_trabajo", "Agregar"))
        self.btn_btn_editar_prove.setText(_translate("ventana_de_trabajo", "Modificar"))
        self.btn_btn_eliminar_prove.setText(_translate("ventana_de_trabajo", "Eliminar"))
        self.btn_btn_info_3.setText(_translate("ventana_de_trabajo", "Detalles"))
        self.label_4.setText(_translate("ventana_de_trabajo", "Inventario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_de_trabajo = QtWidgets.QMainWindow()
    ui = Ui_ventana_de_trabajo()
    ui.setupUi(ventana_de_trabajo)
    ventana_de_trabajo.show()
    sys.exit(app.exec_())
