# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal_trabajo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventana_de_trabajo(object):
    def setupUi(self, ventana_de_trabajo):
        ventana_de_trabajo.setObjectName("ventana_de_trabajo")
        ventana_de_trabajo.resize(1064, 600)
        ventana_de_trabajo.setStyleSheet("#panel_cabecera{\n"
"background-color: rgb(204, 203, 200);\n"
"min-height:40px;\n"
"max-height: 40;\n"
"}\n"
"#panel_opciones_superior{\n"
"    min_height:60px;\n"
"    max-height:60px;\n"
"    background-color: rgb(245, 244, 241);\n"
"}\n"
"#btn_minimizar{\n"
"    background-color:transparent;\n"
"}\n"
"#btn_maximizar{\n"
"    background-color:transparent;\n"
"}\n"
"#btn_cerrar{\n"
"    background-color:transparent;\n"
"}\n"
"#logo{\n"
"    min-width: 50px;\n"
"    max-width: 90px;\n"
"}\n"
"#btn_menu{\n"
"    border: 0px;\n"
"    background-color: transparent;\n"
"}\n"
"#btn_menu:hover {\n"
"border-radius:12px;\n"
"background-color: rgb(212, 234, 247);\n"
"}\n"
"#btn_ventas{\n"
"background-color: rgb(224, 224, 224);\n"
"border-radius:10px;\n"
"}\n"
"#btn_ventas:hover{\n"
"background-color: rgb(212, 234, 247);\n"
"}\n"
"#btn_inventario{\n"
"background-color: rgb(224, 224, 224);\n"
"border-radius:10px;\n"
"}\n"
"#btn_inventario:hover{\n"
"background-color: rgb(212, 234, 247);\n"
"}\n"
"#btn_compras{\n"
"background-color: rgb(224, 224, 224);\n"
"border-radius:10px;\n"
"}\n"
"#btn_compras:hover{\n"
"background-color: rgb(212, 234, 247);\n"
"}\n"
"#btn_provedores{\n"
"background-color: rgb(224, 224, 224);\n"
"border-radius:10px;\n"
"}\n"
"#btn_provedores:hover{\n"
"background-color: rgb(212, 234, 247);\n"
"}\n"
"#btn_clientes{\n"
"background-color: rgb(224, 224, 224);\n"
"border-radius:10px;\n"
"}\n"
"#btn_clientes:hover{\n"
"background-color: rgb(212, 234, 247);\n"
"}\n"
"#panel_opciones_desplegable{\n"
"background-color: rgb(245, 244, 241);\n"
"border-right: 1px solid  rgb(204, 203, 200);\n"
"}\n"
"#panel_cuerpo{\n"
"    background-color: rgb(255, 254, 251);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ventana_de_trabajo)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.panel_ventana = QtWidgets.QWidget(self.centralwidget)
        self.panel_ventana.setStyleSheet("")
        self.panel_ventana.setObjectName("panel_ventana")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.panel_ventana)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.panel_opciones_desplegable = QtWidgets.QWidget(self.panel_ventana)
        self.panel_opciones_desplegable.setMinimumSize(QtCore.QSize(180, 0))
        self.panel_opciones_desplegable.setMaximumSize(QtCore.QSize(180, 16777215))
        self.panel_opciones_desplegable.setStyleSheet("")
        self.panel_opciones_desplegable.setObjectName("panel_opciones_desplegable")
        self.horizontalLayout_2.addWidget(self.panel_opciones_desplegable)
        self.panel_principal_cuerpo = QtWidgets.QWidget(self.panel_ventana)
        self.panel_principal_cuerpo.setObjectName("panel_principal_cuerpo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.panel_principal_cuerpo)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.panel_opciones_superior = QtWidgets.QWidget(self.panel_principal_cuerpo)
        self.panel_opciones_superior.setMinimumSize(QtCore.QSize(0, 0))
        self.panel_opciones_superior.setMaximumSize(QtCore.QSize(16777215, 60))
        self.panel_opciones_superior.setStyleSheet("")
        self.panel_opciones_superior.setObjectName("panel_opciones_superior")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.panel_opciones_superior)
        self.verticalLayout_2.setContentsMargins(5, 2, 2, 2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.panel_contenido_opciones_superior = QtWidgets.QWidget(self.panel_opciones_superior)
        self.panel_contenido_opciones_superior.setMinimumSize(QtCore.QSize(0, 50))
        self.panel_contenido_opciones_superior.setMaximumSize(QtCore.QSize(16777215, 56))
        self.panel_contenido_opciones_superior.setObjectName("panel_contenido_opciones_superior")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.panel_contenido_opciones_superior)
        self.gridLayout_2.setContentsMargins(5, 2, 5, 2)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.panel_btn_menu = QtWidgets.QWidget(self.panel_contenido_opciones_superior)
        self.panel_btn_menu.setMinimumSize(QtCore.QSize(40, 40))
        self.panel_btn_menu.setMaximumSize(QtCore.QSize(40, 40))
        self.panel_btn_menu.setObjectName("panel_btn_menu")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.panel_btn_menu)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_menu = QtWidgets.QPushButton(self.panel_btn_menu)
        self.btn_menu.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_menu.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Downloads/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_menu.setIcon(icon)
        self.btn_menu.setIconSize(QtCore.QSize(30, 30))
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout_4.addWidget(self.btn_menu)
        self.gridLayout_2.addWidget(self.panel_btn_menu, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(385, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.btn_ventas = QtWidgets.QWidget(self.panel_contenido_opciones_superior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ventas.sizePolicy().hasHeightForWidth())
        self.btn_ventas.setSizePolicy(sizePolicy)
        self.btn_ventas.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_ventas.setMaximumSize(QtCore.QSize(80, 56))
        self.btn_ventas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ventas.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.btn_ventas.setStyleSheet("")
        self.btn_ventas.setObjectName("btn_ventas")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.btn_ventas)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.contenedor_img_ventas_superior = QtWidgets.QWidget(self.btn_ventas)
        self.contenedor_img_ventas_superior.setObjectName("contenedor_img_ventas_superior")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.contenedor_img_ventas_superior)
        self.verticalLayout_10.setContentsMargins(15, 5, 15, 5)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.img_ventas_superior = QtWidgets.QLabel(self.contenedor_img_ventas_superior)
        self.img_ventas_superior.setText("")
        self.img_ventas_superior.setPixmap(QtGui.QPixmap("../../../../../Downloads/ventas.svg"))
        self.img_ventas_superior.setScaledContents(True)
        self.img_ventas_superior.setAlignment(QtCore.Qt.AlignCenter)
        self.img_ventas_superior.setObjectName("img_ventas_superior")
        self.verticalLayout_10.addWidget(self.img_ventas_superior)
        self.verticalLayout_9.addWidget(self.contenedor_img_ventas_superior)
        self.lbl_ventas_superior = QtWidgets.QLabel(self.btn_ventas)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_ventas_superior.setFont(font)
        self.lbl_ventas_superior.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ventas_superior.setObjectName("lbl_ventas_superior")
        self.verticalLayout_9.addWidget(self.lbl_ventas_superior)
        self.gridLayout_2.addWidget(self.btn_ventas, 0, 2, 1, 1)
        self.btn_inventario = QtWidgets.QWidget(self.panel_contenido_opciones_superior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_inventario.sizePolicy().hasHeightForWidth())
        self.btn_inventario.setSizePolicy(sizePolicy)
        self.btn_inventario.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_inventario.setMaximumSize(QtCore.QSize(80, 56))
        self.btn_inventario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_inventario.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.btn_inventario.setStyleSheet("")
        self.btn_inventario.setObjectName("btn_inventario")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.btn_inventario)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.contenedor_img_inventario_superior = QtWidgets.QWidget(self.btn_inventario)
        self.contenedor_img_inventario_superior.setObjectName("contenedor_img_inventario_superior")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.contenedor_img_inventario_superior)
        self.verticalLayout_8.setContentsMargins(15, 5, 15, 5)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.img_inventario_superior = QtWidgets.QLabel(self.contenedor_img_inventario_superior)
        self.img_inventario_superior.setText("")
        self.img_inventario_superior.setPixmap(QtGui.QPixmap("../../../../../Downloads/inventario-disponible.svg"))
        self.img_inventario_superior.setScaledContents(True)
        self.img_inventario_superior.setAlignment(QtCore.Qt.AlignCenter)
        self.img_inventario_superior.setObjectName("img_inventario_superior")
        self.verticalLayout_8.addWidget(self.img_inventario_superior)
        self.verticalLayout_7.addWidget(self.contenedor_img_inventario_superior)
        self.lbl_inventario_superior = QtWidgets.QLabel(self.btn_inventario)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_inventario_superior.setFont(font)
        self.lbl_inventario_superior.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inventario_superior.setObjectName("lbl_inventario_superior")
        self.verticalLayout_7.addWidget(self.lbl_inventario_superior)
        self.gridLayout_2.addWidget(self.btn_inventario, 0, 3, 1, 1)
        self.btn_compras = QtWidgets.QWidget(self.panel_contenido_opciones_superior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_compras.sizePolicy().hasHeightForWidth())
        self.btn_compras.setSizePolicy(sizePolicy)
        self.btn_compras.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_compras.setMaximumSize(QtCore.QSize(80, 56))
        self.btn_compras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_compras.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.btn_compras.setStyleSheet("")
        self.btn_compras.setObjectName("btn_compras")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.btn_compras)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.contenedor_img_compras_superior = QtWidgets.QWidget(self.btn_compras)
        self.contenedor_img_compras_superior.setObjectName("contenedor_img_compras_superior")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contenedor_img_compras_superior)
        self.verticalLayout_6.setContentsMargins(15, 5, 15, 5)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.img_compras_superior = QtWidgets.QLabel(self.contenedor_img_compras_superior)
        self.img_compras_superior.setText("")
        self.img_compras_superior.setPixmap(QtGui.QPixmap("../../../../../Downloads/compras.svg"))
        self.img_compras_superior.setScaledContents(True)
        self.img_compras_superior.setAlignment(QtCore.Qt.AlignCenter)
        self.img_compras_superior.setObjectName("img_compras_superior")
        self.verticalLayout_6.addWidget(self.img_compras_superior)
        self.verticalLayout_5.addWidget(self.contenedor_img_compras_superior)
        self.lbl_compras_superior = QtWidgets.QLabel(self.btn_compras)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_compras_superior.setFont(font)
        self.lbl_compras_superior.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_compras_superior.setObjectName("lbl_compras_superior")
        self.verticalLayout_5.addWidget(self.lbl_compras_superior)
        self.gridLayout_2.addWidget(self.btn_compras, 0, 4, 1, 1)
        self.btn_provedores = QtWidgets.QWidget(self.panel_contenido_opciones_superior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_provedores.sizePolicy().hasHeightForWidth())
        self.btn_provedores.setSizePolicy(sizePolicy)
        self.btn_provedores.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_provedores.setMaximumSize(QtCore.QSize(80, 56))
        self.btn_provedores.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_provedores.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.btn_provedores.setStyleSheet("")
        self.btn_provedores.setObjectName("btn_provedores")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.btn_provedores)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.contenedor_img_provedor_superior = QtWidgets.QWidget(self.btn_provedores)
        self.contenedor_img_provedor_superior.setObjectName("contenedor_img_provedor_superior")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.contenedor_img_provedor_superior)
        self.verticalLayout_3.setContentsMargins(15, 5, 15, 5)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.img_provedor_superior = QtWidgets.QLabel(self.contenedor_img_provedor_superior)
        self.img_provedor_superior.setText("")
        self.img_provedor_superior.setPixmap(QtGui.QPixmap("../../../../../Downloads/proveedor.svg"))
        self.img_provedor_superior.setScaledContents(True)
        self.img_provedor_superior.setAlignment(QtCore.Qt.AlignCenter)
        self.img_provedor_superior.setObjectName("img_provedor_superior")
        self.verticalLayout_3.addWidget(self.img_provedor_superior)
        self.verticalLayout_4.addWidget(self.contenedor_img_provedor_superior)
        self.lbl_provedor_superior = QtWidgets.QLabel(self.btn_provedores)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_provedor_superior.setFont(font)
        self.lbl_provedor_superior.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_provedor_superior.setObjectName("lbl_provedor_superior")
        self.verticalLayout_4.addWidget(self.lbl_provedor_superior)
        self.gridLayout_2.addWidget(self.btn_provedores, 0, 5, 1, 1)
        self.btn_clientes = QtWidgets.QWidget(self.panel_contenido_opciones_superior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clientes.sizePolicy().hasHeightForWidth())
        self.btn_clientes.setSizePolicy(sizePolicy)
        self.btn_clientes.setMinimumSize(QtCore.QSize(80, 40))
        self.btn_clientes.setMaximumSize(QtCore.QSize(80, 56))
        self.btn_clientes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clientes.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.btn_clientes.setStyleSheet("")
        self.btn_clientes.setObjectName("btn_clientes")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.btn_clientes)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.contenedor_img_cliente_superior = QtWidgets.QWidget(self.btn_clientes)
        self.contenedor_img_cliente_superior.setObjectName("contenedor_img_cliente_superior")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.contenedor_img_cliente_superior)
        self.verticalLayout_12.setContentsMargins(15, 5, 15, 5)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.img_cliente_superior = QtWidgets.QLabel(self.contenedor_img_cliente_superior)
        self.img_cliente_superior.setText("")
        self.img_cliente_superior.setPixmap(QtGui.QPixmap("../../../../../Downloads/atencion-al-cliente.svg"))
        self.img_cliente_superior.setScaledContents(True)
        self.img_cliente_superior.setAlignment(QtCore.Qt.AlignCenter)
        self.img_cliente_superior.setObjectName("img_cliente_superior")
        self.verticalLayout_12.addWidget(self.img_cliente_superior)
        self.verticalLayout_11.addWidget(self.contenedor_img_cliente_superior)
        self.lbl_clientes_superior = QtWidgets.QLabel(self.btn_clientes)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_clientes_superior.setFont(font)
        self.lbl_clientes_superior.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_clientes_superior.setObjectName("lbl_clientes_superior")
        self.verticalLayout_11.addWidget(self.lbl_clientes_superior)
        self.gridLayout_2.addWidget(self.btn_clientes, 0, 6, 1, 1)
        self.verticalLayout_2.addWidget(self.panel_contenido_opciones_superior)
        self.verticalLayout.addWidget(self.panel_opciones_superior)
        self.panel_cuerpo = QtWidgets.QWidget(self.panel_principal_cuerpo)
        self.panel_cuerpo.setObjectName("panel_cuerpo")
        self.verticalLayout.addWidget(self.panel_cuerpo)
        self.horizontalLayout_2.addWidget(self.panel_principal_cuerpo)
        self.gridLayout.addWidget(self.panel_ventana, 1, 0, 1, 1)
        self.panel_cabecera = QtWidgets.QWidget(self.centralwidget)
        self.panel_cabecera.setObjectName("panel_cabecera")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.panel_cabecera)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo = QtWidgets.QLabel(self.panel_cabecera)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../../../../../Downloads/logo_sinfondo_vector.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.horizontalLayout.addWidget(self.logo)
        spacerItem1 = QtWidgets.QSpacerItem(869, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_minimizar = QtWidgets.QPushButton(self.panel_cabecera)
        self.btn_minimizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_minimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../Downloads/minimizar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimizar.setIcon(icon1)
        self.btn_minimizar.setIconSize(QtCore.QSize(20, 20))
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.horizontalLayout.addWidget(self.btn_minimizar)
        self.btn_maximizar = QtWidgets.QPushButton(self.panel_cabecera)
        self.btn_maximizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_maximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../Downloads/maximizar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximizar.setIcon(icon2)
        self.btn_maximizar.setIconSize(QtCore.QSize(20, 20))
        self.btn_maximizar.setObjectName("btn_maximizar")
        self.horizontalLayout.addWidget(self.btn_maximizar)
        self.btn_cerrar = QtWidgets.QPushButton(self.panel_cabecera)
        self.btn_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../Downloads/img_cerrar.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cerrar.setIcon(icon3)
        self.btn_cerrar.setIconSize(QtCore.QSize(20, 20))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout.addWidget(self.btn_cerrar)
        self.gridLayout.addWidget(self.panel_cabecera, 0, 0, 1, 1)
        ventana_de_trabajo.setCentralWidget(self.centralwidget)

        self.retranslateUi(ventana_de_trabajo)
        QtCore.QMetaObject.connectSlotsByName(ventana_de_trabajo)

    def retranslateUi(self, ventana_de_trabajo):
        _translate = QtCore.QCoreApplication.translate
        ventana_de_trabajo.setWindowTitle(_translate("ventana_de_trabajo", "MainWindow"))
        self.lbl_ventas_superior.setText(_translate("ventana_de_trabajo", "Ventas"))
        self.lbl_inventario_superior.setText(_translate("ventana_de_trabajo", "Inventario"))
        self.lbl_compras_superior.setText(_translate("ventana_de_trabajo", "Compras"))
        self.lbl_provedor_superior.setText(_translate("ventana_de_trabajo", "Provedores"))
        self.lbl_clientes_superior.setText(_translate("ventana_de_trabajo", "Clientes"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ventana_de_trabajo = QtWidgets.QMainWindow()
    ui = Ui_ventana_de_trabajo()
    ui.setupUi(ventana_de_trabajo)
    ventana_de_trabajo.show()
    sys.exit(app.exec_())
